l_english:
 
 ###################################
 ##### Monthly Progress Values #####
 ###################################
 
 # Datafunctions (no translation needed)
 
 ten_months_monthly_num:0 "#TOOLTIP:ten_months_monthly_tt #V;L [GetPlayer.MakeScope.ScriptValue('ten_months_progress')|0]%#!#!"
 ten_months_monthly_tt:0 "$POD_journey_time_until_completion$ #V [GetPlayer.MakeScope.ScriptValue('ten_months_progress_years')|0] $POD_journey_years$, [GetPlayer.MakeScope.ScriptValue('ten_months_progress_months')|0] $POD_journey_months$#!\n\n[GetPlayer.MakeScope.GetScriptValueDesc('ten_months_progress')]"
 ten_months_monthly_num_current:0 "#TOOLTIP:ten_months_monthly_tt_current #V;L [GetPlayer.MakeScope.ScriptValue('ten_months_progress')|0]%#!#!"
 ten_months_monthly_tt_current:0 "$POD_journey_time_remaining$ #V [GetPlayer.MakeScope.ScriptValue('ten_months_progress_years_current')|0] $POD_journey_years$, [GetPlayer.MakeScope.ScriptValue('ten_months_progress_months_current')|0] $POD_journey_months$#!\n\n[GetPlayer.MakeScope.GetScriptValueDesc('ten_months_progress')]"
 
 twelve_months_monthly_num:0 "#TOOLTIP:twelve_months_monthly_tt #V;L [GetPlayer.MakeScope.ScriptValue('twelve_months_progress')|1]%#!#!"
 twelve_months_monthly_tt:0 "$POD_journey_time_until_completion$ #V [GetPlayer.MakeScope.ScriptValue('twelve_months_progress_years')|0] $POD_journey_years$, [GetPlayer.MakeScope.ScriptValue('twelve_months_progress_months')|0] $POD_journey_months$#!\n\n[GetPlayer.MakeScope.GetScriptValueDesc('twelve_months_progress')]"
 twelve_months_monthly_num_current:0 "#TOOLTIP:twelve_months_monthly_tt_current #V;L [GetPlayer.MakeScope.ScriptValue('twelve_months_progress')|1]%#!#!"
 twelve_months_monthly_tt_current:0 "$POD_journey_time_remaining$ #V [GetPlayer.MakeScope.ScriptValue('twelve_months_progress_years_current')|0] $POD_journey_years$, [GetPlayer.MakeScope.ScriptValue('twelve_months_progress_months_current')|0] $POD_journey_months$#!\n\n[GetPlayer.MakeScope.GetScriptValueDesc('twelve_months_progress')]"
 
 five_years_monthly_num:0 "#TOOLTIP:five_years_monthly_tt #V;L [GetPlayer.MakeScope.ScriptValue('five_years_progress')|1]%#!#!"
 five_years_monthly_tt:0 "$POD_journey_time_until_completion$ #V [GetPlayer.MakeScope.ScriptValue('five_years_progress_years')|0] $POD_journey_years$, [GetPlayer.MakeScope.ScriptValue('five_years_progress_months')|0] $POD_journey_months$#!\n\n[GetPlayer.MakeScope.GetScriptValueDesc('five_years_progress')]"
 five_years_monthly_num_current:0 "#TOOLTIP:five_years_monthly_tt_current #V;L [GetPlayer.MakeScope.ScriptValue('five_years_progress')|1]%#!#!"
 five_years_monthly_tt_current:0 "$POD_journey_time_remaining$ #V [GetPlayer.MakeScope.ScriptValue('five_years_progress_years_current')|0] $POD_journey_years$, [GetPlayer.MakeScope.ScriptValue('five_years_progress_months_current')|0] $POD_journey_months$#!\n\n[GetPlayer.MakeScope.GetScriptValueDesc('five_years_progress')]"
 
 ten_years_monthly_num:0 "#TOOLTIP:ten_years_monthly_tt #V;L [GetPlayer.MakeScope.ScriptValue('ten_years_progress')|1]%#!#!"
 ten_years_monthly_tt:0 "$POD_journey_time_until_completion$ #V [GetPlayer.MakeScope.ScriptValue('ten_years_progress_years')|0] $POD_journey_years$, [GetPlayer.MakeScope.ScriptValue('ten_years_progress_months')|0] $POD_journey_months$#!\n\n[GetPlayer.MakeScope.GetScriptValueDesc('ten_years_progress')]"
 ten_years_monthly_num_current:0 "#TOOLTIP:ten_years_monthly_tt_current #V;L [GetPlayer.MakeScope.ScriptValue('ten_years_progress')|1]%#!#!"
 ten_years_monthly_tt_current:0 "$POD_journey_time_remaining$ #V [GetPlayer.MakeScope.ScriptValue('ten_years_progress_years_current')|0] $POD_journey_years$, [GetPlayer.MakeScope.ScriptValue('ten_years_progress_months_current')|0] $POD_journey_months$#!\n\n[GetPlayer.MakeScope.GetScriptValueDesc('ten_years_progress')]"
 
 werewolf_training_monthly_num:0 "#TOOLTIP:werewolf_training_monthly_tt #V;L [GetPlayer.MakeScope.ScriptValue('werewolf_training_progress')|1]%#!#!"
 werewolf_training_monthly_tt:0 "$POD_journey_time_until_completion$ #V [GetPlayer.MakeScope.ScriptValue('werewolf_training_progress_years')|0] $POD_journey_years$, [GetPlayer.MakeScope.ScriptValue('werewolf_training_progress_months')|0] $POD_journey_months$#!\n\n[GetPlayer.MakeScope.GetScriptValueDesc('werewolf_training_progress')]"
 werewolf_training_monthly_num_current:0 "#TOOLTIP:werewolf_training_monthly_tt_current #V;L [GetPlayer.MakeScope.ScriptValue('werewolf_training_progress')|1]%#!#!"
 werewolf_training_monthly_tt_current:0 "$POD_journey_time_remaining$ #V [GetPlayer.MakeScope.ScriptValue('werewolf_training_progress_years_current')|0] $POD_journey_years$, [GetPlayer.MakeScope.ScriptValue('werewolf_training_progress_months_current')|0] $POD_journey_months$#!\n\n[GetPlayer.MakeScope.GetScriptValueDesc('werewolf_training_progress')]"
 
 seek_knowledge_monthly_num:0 "#TOOLTIP:seek_knowledge_monthly_tt #V;L [GetPlayer.MakeScope.ScriptValue('seek_knowledge_progress_not_current')|1]%#!#!"
 seek_knowledge_monthly_tt:0 "$POD_journey_time_until_completion$ #V [GetPlayer.MakeScope.ScriptValue('seek_knowledge_progress_years')|0] $POD_journey_years$, [GetPlayer.MakeScope.ScriptValue('seek_knowledge_progress_months')|0] $POD_journey_months$#!\n\n[GetPlayer.MakeScope.GetScriptValueDesc('seek_knowledge_progress_not_current')]\n\n$POD_journey_progress_seek_knowledge_gui$"
 seek_knowledge_monthly_num_current:0 "#TOOLTIP:seek_knowledge_monthly_tt_current #V;L [GetPlayer.MakeScope.ScriptValue('seek_knowledge_progress')|1]%#!#!"
 seek_knowledge_monthly_tt_current:0 "$POD_journey_time_remaining$ #V [GetPlayer.MakeScope.ScriptValue('seek_knowledge_progress_years_current')|0] $POD_journey_years$, [GetPlayer.MakeScope.ScriptValue('seek_knowledge_progress_months_current')|0] $POD_journey_months$#!\n\n[GetPlayer.MakeScope.GetScriptValueDesc('seek_knowledge_progress')]"
 
 find_artifact_monthly_num:0 "#TOOLTIP:find_artifact_monthly_tt #V;L [GetPlayer.MakeScope.ScriptValue('find_artifact_progress')|1]%#!#!"
 find_artifact_monthly_tt:0 "$POD_journey_time_until_completion$ #V [GetPlayer.MakeScope.ScriptValue('find_artifact_progress_years')|0] $POD_journey_years$, [GetPlayer.MakeScope.ScriptValue('find_artifact_progress_months')|0] $POD_journey_months$#!\n\n[GetPlayer.MakeScope.GetScriptValueDesc('find_artifact_progress')]"
 find_artifact_monthly_num_current:0 "#TOOLTIP:find_artifact_monthly_tt_current #V;L [GetPlayer.MakeScope.ScriptValue('find_artifact_progress')|1]%#!#!"
 find_artifact_monthly_tt_current:0 "$POD_journey_time_remaining$ #V [GetPlayer.MakeScope.ScriptValue('find_artifact_progress_years_current')|0] $POD_journey_years$, [GetPlayer.MakeScope.ScriptValue('find_artifact_progress_months_current')|0] $POD_journey_months$#!\n\n[GetPlayer.MakeScope.GetScriptValueDesc('find_artifact_progress')]"
 
 # Text starts here
 
 instant_monthly_num:0 "Instant"
 instant_monthly_num_current:0 "$instant_monthly_num$"
 
 
 POD_journey_time_until_completion:0 "Time until completion:"
 POD_journey_time_remaining:0 "Time remaining:"
 POD_journey_years:0 "years"
 POD_journey_months:0 "months"
 
 
 POD_journey_progress_base:0 "Base [planning_speed|E]"
 
 POD_journey_progress_diplomacy:0 "Your [diplomacy|E] #weak (capped at [EmptyScope.ScriptValue('coterie_skill_hardcap')])#!"
 POD_journey_progress_diplomacy_coterie:0 "[diplomacy|E] of $POD_player_coterie$ #weak (capped at [EmptyScope.ScriptValue('coterie_skill_hardcap')])#!"
 POD_journey_progress_martial:0 "Your [martial|E] #weak (capped at [EmptyScope.ScriptValue('coterie_skill_hardcap')])#!"
 POD_journey_progress_martial_coterie:0 "[martial|E] of $POD_player_coterie$ #weak (capped at [EmptyScope.ScriptValue('coterie_skill_hardcap')])#!"
 POD_journey_progress_stewardship:0 "Your [stewardship|E] #weak (capped at [EmptyScope.ScriptValue('coterie_skill_hardcap')])#!"
 POD_journey_progress_stewardship_coterie:0 "[stewardship|E] of $POD_player_coterie$ #weak (capped at [EmptyScope.ScriptValue('coterie_skill_hardcap')])#!"
 POD_journey_progress_intrigue:0 "Your [intrigue|E] #weak (capped at (capped at [EmptyScope.ScriptValue('coterie_skill_hardcap')])#!"
 POD_journey_progress_intrigue_coterie:0 "[intrigue|E] of $POD_player_coterie$ #weak (capped at [EmptyScope.ScriptValue('coterie_skill_hardcap')])#!"
 POD_journey_progress_learning:0 "Your [learning|E] #weak (capped at [EmptyScope.ScriptValue('coterie_skill_hardcap')])#!"
 POD_journey_progress_learning_coterie:0 "[learning|E] of $POD_player_coterie$ #weak (capped at [EmptyScope.ScriptValue('coterie_skill_hardcap')])#!"
 
 POD_journey_progress_court_tutor_none:0 "You don't employ a [GetCourtPositionType('court_tutor_court_position').GetName()]"
 POD_journey_progress_court_tutor_2:0 "Your [GetCourtPositionType('court_tutor_court_position').GetName()] has Poor [aptitude|E]"
 POD_journey_progress_court_tutor_3:0 "Your [GetCourtPositionType('court_tutor_court_position').GetName()] has Adequate [aptitude|E]"
 POD_journey_progress_court_tutor_4:0 "Your [GetCourtPositionType('court_tutor_court_position').GetName()] has Good [aptitude|E]"
 POD_journey_progress_court_tutor_5:0 "Your [GetCourtPositionType('court_tutor_court_position').GetName()] has Excellent [aptitude|E]"
 
 POD_journey_progress_antiquarian_none:0 "You don't employ an [GetCourtPositionType('antiquarian_court_position').GetName()]"
 POD_journey_progress_antiquarian_2:0 "Your [GetCourtPositionType('antiquarian_court_position').GetName()] has Poor [aptitude|E]"
 POD_journey_progress_antiquarian_3:0 "Your [GetCourtPositionType('antiquarian_court_position').GetName()] has Adequate [aptitude|E]"
 POD_journey_progress_antiquarian_4:0 "Your [GetCourtPositionType('antiquarian_court_position').GetName()] has Good [aptitude|E]"
 POD_journey_progress_antiquarian_5:0 "Your [GetCourtPositionType('antiquarian_court_position').GetName()] has Excellent [aptitude|E]"
 
 POD_journey_progress_seek_knowledge:0 "#V [GetPlayer.MakeScope.ScriptValue('seek_knowledge_coterie_member_count')]#! [Select_CString( EqualTo_CFixedPoint( GetPlayer.MakeScope.ScriptValue('seek_knowledge_coterie_member_count'), '(CFixedPoint)1' ), 'member', 'members' )] of $POD_player_coterie$ [Select_CString( EqualTo_CFixedPoint( GetPlayer.MakeScope.ScriptValue('seek_knowledge_coterie_member_count'), '(CFixedPoint)1' ), 'knows', 'know' )] this ability"
 POD_journey_progress_seek_knowledge_gui:0 "#help [planning_speed|E] will further increase for every member of your [GetPlayer.Custom('PODCoterie')] who already knows this ability.#!"
 
 
 ##### Value breakdown formats
 
 POD_PROGRESS_FORMAT_POSITIVE:0 "$KEY$: #P +$VALUE|2$#!"
 POD_PROGRESS_FORMAT_NEGATIVE:0 "$KEY$: #N $VALUE|2$#!"
 
 POD_PROGRESS_FORMAT_PERCENTAGE_POSITIVE:0 "$KEY$: #P $VALUE|=0%$#!"